// Inventory data for the retail shop
const inventory = [
  { id: 1, name: 'Chini', hindiName: 'चीनी', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 2, name: 'Boora', hindiName: 'बूरा', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 3, name: 'Besan Motia', hindiName: 'बेसन मोटिया', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 4, name: 'Aata Barik', hindiName: 'आटा बारीक', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 5, name: 'Maida', hindiName: 'मैदा', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 6, name: 'Suji', hindiName: 'सूजी', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 7, name: 'Ghee Desi', hindiName: 'घी देसी', price: 50, unit: 'पीपा', stock: 100 },
  { id: 8, name: 'Tel Moongfali', hindiName: 'तेल मूंगफली', price: 50, unit: 'पीपा', stock: 100 },
  { id: 9, name: 'Tel', hindiName: 'तेल', price: 50, unit: 'पीपा', stock: 100 },
  { id: 10, name: 'Kaju', hindiName: 'काजू', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 11, name: 'Badam', hindiName: 'बादाम', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 12, name: 'Pista Saabut', hindiName: 'पिस्ता साबुत', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 13, name: '4 Piece Kaju', hindiName: '4 पीस काजू', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 14, name: 'Kishmish', hindiName: 'किशमिश', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 15, name: 'Cutting Badam', hindiName: 'कटिंग बादाम', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 16, name: 'Cutting Pista', hindiName: 'कटिंग पिस्ता', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 17, name: 'Elaichi', hindiName: 'इलायची', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 18, name: 'Kesar', hindiName: 'केसर', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 19, name: 'Peela Color', hindiName: 'पीला कलर', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 20, name: 'Orange Color', hindiName: 'ऑरेंज कलर', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 21, name: 'Hara Color', hindiName: 'हरा कलर', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 22, name: 'Coffee Color', hindiName: 'कॉफी कलर', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 23, name: 'Chandi Vark', hindiName: 'चांदी वर्क', price: 50, unit: 'गड्डी', stock: 100 },
  { id: 24, name: 'Heeng', hindiName: 'हींग', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 25, name: 'Cutter', hindiName: 'कटर', price: 50, unit: '1', stock: 100 },
  { id: 26, name: 'Butter Paper', hindiName: 'बटर पेपर', price: 50, unit: '1', stock: 100 },
  { id: 27, name: 'Phool Makhana', hindiName: 'फूल मखाना', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 28, name: 'Wafers', hindiName: 'वेफर्स', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 29, name: 'Double Chawal', hindiName: 'डबल चावल', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 30, name: 'Ararot', hindiName: 'अरारोट', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 31, name: 'Moth', hindiName: 'मोट', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 32, name: 'Meetha Soda', hindiName: 'मीठा सोडा', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 33, name: 'Kala Chana', hindiName: 'काला चना', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 34, name: 'Moongfali Dana', hindiName: 'मूंगफली दाना', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 35, name: 'Sooji Saabut', hindiName: 'सूजी साबुत', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 36, name: 'Poha', hindiName: 'पोहा', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 37, name: 'Chhola', hindiName: 'छोला', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 38, name: 'Moong Mogar', hindiName: 'मूंग मोगर', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 39, name: 'Udad Mogar', hindiName: 'उड़द मोगर', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 40, name: 'Chana Dal', hindiName: 'चना दाल', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 41, name: 'Arhar Dal', hindiName: 'अरहर दाल', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 42, name: 'Papad', hindiName: 'पापड़', price: 50, unit: 'नग', stock: 100 },
  { id: 43, name: 'Cutting Papad', hindiName: 'कटिंग पापड़', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 44, name: '0 No. Sev', hindiName: '0 नं. सेव', price: 50, unit: 'ग्राम', stock: 100 },
  { id: 45, name: 'Bikaneri Sev', hindiName: 'बीकानेरी सेव', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 46, name: 'Noodles', hindiName: 'नूडल्स', price: 50, unit: 'पैकेट', stock: 100 },
  { id: 47, name: 'Pasta 2 Prakar', hindiName: 'पास्ता 2 प्रकार', price: 50, unit: 'किग्रा', stock: 100 },
  { id: 48, name: 'Tomato Puree', hindiName: 'टमाटर प्यूरी', price: 50, unit: '3', stock: 100 },
  { id: 49, name: 'Tomato Sauce', hindiName: 'टमाटर सॉस', price: 50, unit: '16', stock: 100 },
  { id: 50, name: 'Sirka', hindiName: 'सिरका', price: 50, unit: '1', stock: 100 },
  { id: 51, name: 'Red Chilli', hindiName: 'रेड चिली', price: 50, unit: '5', stock: 100 },
  { id: 52, name: 'Coffee', hindiName: 'कॉफी', price: 50, unit: 'ग्राम', stock: 100 },
];

export default inventory; 