// Inventory data for the retail shop
const inventory = [
  { id: 1, name: 'Chini', hindiName: 'चीनी', unit: 'किग्रा' },
  { id: 2, name: 'Boora', hindiName: 'बूरा', unit: 'किग्रा' },
  { id: 3, name: 'Besan Motia', hindiName: 'बेसन मोटिया', unit: 'किग्रा' },
  { id: 4, name: 'Aata Barik', hindiName: 'आटा बारीक', unit: 'किग्रा' },
  { id: 5, name: 'Maida', hindiName: 'मैदा', unit: 'किग्रा' },
  { id: 6, name: 'Suji', hindiName: 'सूजी', unit: 'किग्रा' },
  { id: 7, name: 'Ghee Desi', hindiName: 'घी देसी', unit: 'पीपा' },
  { id: 8, name: 'Tel Moongfali', hindiName: 'तेल मूंगफली', unit: 'पीपा' },
  { id: 9, name: 'Tel', hindiName: 'तेल', unit: 'पीपा' },
  { id: 10, name: 'Kaju', hindiName: 'काजू', unit: 'किग्रा' },
  { id: 11, name: 'Badam', hindiName: 'बादाम', unit: 'किग्रा' },
  { id: 12, name: 'Pista Saabut', hindiName: 'पिस्ता साबुत', unit: 'किग्रा' },
  { id: 13, name: '4 Piece Kaju', hindiName: '4 पीस काजू', unit: 'किग्रा' },
  { id: 14, name: 'Kishmish', hindiName: 'किशमिश', unit: 'ग्राम' },
  { id: 15, name: 'Cutting Badam', hindiName: 'कटिंग बादाम', unit: 'ग्राम' },
  { id: 16, name: 'Cutting Pista', hindiName: 'कटिंग पिस्ता', unit: 'ग्राम' },
  { id: 17, name: 'Elaichi', hindiName: 'इलायची', unit: 'ग्राम' },
  { id: 18, name: 'Kesar', hindiName: 'केसर', unit: 'ग्राम' },
  { id: 19, name: 'Peela Color', hindiName: 'पीला कलर', unit: 'ग्राम' },
  { id: 20, name: 'Orange Color', hindiName: 'ऑरेंज कलर', unit: 'ग्राम' },
  { id: 21, name: 'Hara Color', hindiName: 'हरा कलर', unit: 'ग्राम' },
  { id: 22, name: 'Coffee Color', hindiName: 'कॉफी कलर', unit: 'ग्राम' },
  { id: 23, name: 'Chandi Vark', hindiName: 'चांदी वर्क', unit: 'गड्डी' },
  { id: 24, name: 'Heeng', hindiName: 'हींग', unit: 'ग्राम' },
  { id: 25, name: 'Cutter', hindiName: 'कटर', unit: '1' },
  { id: 26, name: 'Butter Paper', hindiName: 'बटर पेपर', unit: '1' },
  { id: 27, name: 'Phool Makhana', hindiName: 'फूल मखाना', unit: 'ग्राम' },
  { id: 28, name: 'Wafers', hindiName: 'वेफर्स', unit: 'किग्रा' },
  { id: 29, name: 'Double Chawal', hindiName: 'डबल चावल', unit: 'किग्रा' },
  { id: 30, name: 'Ararot', hindiName: 'अरारोट', unit: 'किग्रा' },
  { id: 31, name: 'Moth', hindiName: 'मोट', unit: 'ग्राम' },
  { id: 32, name: 'Meetha Soda', hindiName: 'मीठा सोडा', unit: 'ग्राम' },
  { id: 33, name: 'Kala Chana', hindiName: 'काला चना', unit: 'ग्राम' },
  { id: 34, name: 'Moongfali Dana', hindiName: 'मूंगफली दाना', unit: 'किग्रा' },
  { id: 35, name: 'Sooji Saabut', hindiName: 'सूजी साबुत', unit: 'ग्राम' },
  { id: 36, name: 'Poha', hindiName: 'पोहा', unit: 'किग्रा' },
  { id: 37, name: 'Chhola', hindiName: 'छोला', unit: 'किग्रा' },
  { id: 38, name: 'Moong Mogar', hindiName: 'मूंग मोगर', unit: 'किग्रा' },
  { id: 39, name: 'Udad Mogar', hindiName: 'उड़द मोगर', unit: 'किग्रा' },
  { id: 40, name: 'Chana Dal', hindiName: 'चना दाल', unit: 'किग्रा' },
  { id: 41, name: 'Arhar Dal', hindiName: 'अरहर दाल', unit: 'किग्रा' },
  { id: 42, name: 'Papad', hindiName: 'पापड़', unit: 'नग' },
  { id: 43, name: 'Cutting Papad', hindiName: 'कटिंग पापड़', unit: 'ग्राम' },
  { id: 44, name: '0 No. Sev', hindiName: '0 नं. सेव', unit: 'ग्राम' },
  { id: 45, name: 'Bikaneri Sev', hindiName: 'बीकानेरी सेव', unit: 'किग्रा' },
  { id: 46, name: 'Noodles', hindiName: 'नूडल्स', unit: 'पैकेट' },
  { id: 47, name: 'Pasta 2 Prakar', hindiName: 'पास्ता 2 प्रकार', unit: 'किग्रा' },
  { id: 48, name: 'Tomato Puree', hindiName: 'टमाटर प्यूरी', unit: '3' },
  { id: 49, name: 'Tomato Sauce', hindiName: 'टमाटर सॉस', unit: '16' },
  { id: 50, name: 'Sirka', hindiName: 'सिरका', unit: '1' },
  { id: 51, name: 'Red Chilli', hindiName: 'रेड चिली', unit: '5' },
  { id: 52, name: 'Coffee', hindiName: 'कॉफी', unit: 'ग्राम' }
];

export default inventory; 